# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/design_1_PmodBT2_0_0.xci
# IP: The module: 'design_1_PmodBT2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] -quiet

# IP: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] -quiet

# IP: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_ooc.xdc

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/design_1_PmodBT2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_ooc.xdc

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: C:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/design_1_PmodBT2_0_0.xci
# IP: The module: 'design_1_PmodBT2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] -quiet

# IP: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] -quiet

# IP: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_ooc.xdc

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/design_1_PmodBT2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_ooc.xdc

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ECE532/bluetooth_nv/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
