// -------------------------------------------------------------
// 
// File Name: /home/shahryar/Desktop/ECE532/TestHDLMatlab/hdlsrc/audio_setup/alpha285Hz_Trig1.v
// Created: 2020-03-22 00:50:48
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha285Hz_Trig1
// Source Path: audio_setup/audio_core/Drum/285Hz Trig1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha285Hz_Trig1
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   In1;
  output  signed [19:0] Out1;  // sfix20_En16


  reg [22:0] HDL_Counter6_out1;  // ufix23
  wire signed [22:0] Data_Type_Conversion6_out1;  // sfix23_En19
  wire signed [45:0] Trig1_out1;  // sfix46_En39
  wire signed [19:0] Data_Type_Conversion7_out1;  // sfix20_En16


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 3
  //  count to value  = 524286
  always @(posedge clk or posedge reset)
    begin : HDL_Counter6_process
      if (reset == 1'b1) begin
        HDL_Counter6_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          if (In1 == 1'b1) begin
            if (HDL_Counter6_out1 == 23'b00001111111111111111110) begin
              HDL_Counter6_out1 <= 23'b00000000000000000000000;
            end
            else begin
              HDL_Counter6_out1 <= HDL_Counter6_out1 + 23'b00000000000000000000011;
            end
          end
        end
      end
    end


  assign Data_Type_Conversion6_out1 = HDL_Counter6_out1;


  Trig1_block u_Trig1 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .In1(HDL_Counter6_out1),  // ufix23
                       .In2(Data_Type_Conversion6_out1),  // sfix23_En19
                       .Out1(Trig1_out1)  // sfix46_En39
                       );
  assign Data_Type_Conversion7_out1 = Trig1_out1[42:23];


  assign Out1 = Data_Type_Conversion7_out1;

endmodule  // alpha285Hz_Trig1

