# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/design_1_design_1_wrapper_0_0.xci
# IP: The module: 'design_1_design_1_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ov7670_capture_0_0/design_1_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_capture_0_0 || ORIG_REF_NAME==design_1_ov7670_capture_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ov7670_controller_0_0/design_1_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_0 || ORIG_REF_NAME==design_1_ov7670_controller_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ov7670_vga_0_0/design_1_ov7670_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_vga_0_0 || ORIG_REF_NAME==design_1_ov7670_vga_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_finger_detection_0_0/design_1_finger_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_finger_detection_0_0 || ORIG_REF_NAME==design_1_finger_detection_0_0} -quiet] -quiet

# XDC: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_design_1_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ooc.xdc

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/design_1_design_1_wrapper_0_0.xci
# IP: The module: 'design_1_design_1_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ov7670_capture_0_0/design_1_ov7670_capture_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_capture_0_0 || ORIG_REF_NAME==design_1_ov7670_capture_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ov7670_controller_0_0/design_1_ov7670_controller_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_0 || ORIG_REF_NAME==design_1_ov7670_controller_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ov7670_vga_0_0/design_1_ov7670_vga_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_vga_0_0 || ORIG_REF_NAME==design_1_ov7670_vga_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_debounce_0_0/design_1_debounce_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_finger_detection_0_0/design_1_finger_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_finger_detection_0_0 || ORIG_REF_NAME==design_1_finger_detection_0_0} -quiet] -quiet

# XDC: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_design_1_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/ECE532/ECE532_Group5/bluetooth_nddr/bluetooth.srcs/sources_1/bd/design_1/ip/design_1_design_1_wrapper_0_0/src/design_1_ooc.xdc
